### ISSUE TITLE
CI os matrix?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [google/forma#37]
I read that the projects wants to target/support multiple OS.

But looking at CI.yml, it only seems to perform CI on ubuntu-latest.

How do you ensure it continues to work on those other OS?

Could an old.matrix be added in the CI GitHub Action workflow to test on the platforms GH Actions support (macos-latest at least?)?

**Comment by dragostis** [comment]
Since forma only has two platform-specific dependencies, Rayon and wgpu, both of which offering guarantees on the platforms they run on, I don't think it makes sense to test their functionality as well. At least, not at this stage.

What would make more sense would be to add performance measurements to the CI in order to find regressions, but I would rather wait until wgpu has timestamps implemented on macOS before working on that.
